### ISSUE TITLE
Missing dependancy in composer ( rinvex/support )

### ISSUE THREAD

**Issue by DrPandalot** [rinvex/addresses#14]
Repro :
1) Install fresh laravel 5.5 project ( scaffold, migrate, add user )
2) Follow procedure to install rinvex / addresses
3) Open artisan tinker
4) use :  " $user->addresses()->create([  ... "  example from installation page.

Extra :
Try install said dependancy, it should fail with :

  Problem 1
    - Installation request for rinvex/support dev-master -> satisfiable by rinvex/support[dev-master].
    - Conclusion: remove laravel/framework v5.5.14
    - Conclusion: don't install laravel/framework v5.5.14

**Comment by Omranic** [comment]
Sorry for not mentioning this in the docs, but you can only use **`develop`** branch for now, use: **`composer require rinvex/attributes:dev-develop`** it should work smoothly even it's still in development. Note that this package still not yet tagged as stable. Please feel free to reopen this issue or a new issue, if you need further assistance :)
