### ISSUE TITLE
findByDistance Unknown column 'addresses.lat' in 'where clause'

### ISSUE THREAD

**Issue by lemonjp** [rinvex/addresses#22]
I've got this sql error when i using findByDistance method.

> Column not found: 1054 Unknown column 'addresses.lat' in 'where clause'

Because jackpopp/geodistance's "within" method need lat and lng column instead of latitude and longitude.

Do you have any plan to change that column name from latitude-longitude to lat-lng?

**Comment by lemonjp** [comment]
And you don't need ->get() method when you using findByDistance as mentioned by README.

```php
// Find all users within 5 kilometers radius from the latitude/longitude 31.2467601/29.9020376
$fiveKmAddresses = \App\Models\User::findByDistance(5, 'kilometers', '31.2467601', '29.9020376')->get();
```
to this.

```php
// Find all users within 5 kilometers radius from the latitude/longitude 31.2467601/29.9020376
$fiveKmAddresses = \App\Models\User::findByDistance(5, 'kilometers', '31.2467601', '29.9020376');
```
Anyway, I've quick solved this issue. To do so, I've eventually overridden GeoDistanceTrait.php,  Address.php and Addressable.php.

**Comment by blwsh** [comment]
I also have this issue in version 3.0.1

**Comment by Omranic** [comment]
Thank you for your patience, this is now fixed in https://github.com/rinvex/laravel-addresses/commit/94abddf227b44fcbdeec691b7577c20bde189668
