### ISSUE TITLE
Not working for laravel 5.7

### ISSUE THREAD

**Issue by naveen84123** [rinvex/addresses#23]
while installing it not able to install with laravel 5.7

**Comment by apydevs** [comment]
@naveen84123  works fine for me? 
what are you having trouble with?

**Comment by JayAhrDe** [comment]
On laravel 5.8 I'm getting this. Might be the same: I skipped 5.7

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install illuminate/database v5.7.28
    - Conclusion: don't install illuminate/database v5.7.27
    - Conclusion: don't install illuminate/database v5.7.26
    - Conclusion: don't install illuminate/database v5.7.23
    - Conclusion: don't install illuminate/database v5.7.22
    - Conclusion: don't install illuminate/database v5.7.21
    - Conclusion: don't install illuminate/database v5.7.20
    - Conclusion: don't install illuminate/database 5.7.19
    - Conclusion: don't install illuminate/database 5.7.18
    - Conclusion: don't install illuminate/database 5.7.17
    - Conclusion: don't install illuminate/database v5.7.15
    - Conclusion: don't install illuminate/database v5.7.11
    - Conclusion: don't install illuminate/database v5.7.10
    - Conclusion: don't install illuminate/database v5.7.9
    - Conclusion: don't install illuminate/database v5.7.8
    - Conclusion: don't install illuminate/database v5.7.7
    - Conclusion: don't install illuminate/database v5.7.6
    - Conclusion: don't install illuminate/database v5.7.5
    - Conclusion: don't install illuminate/database v5.7.4
    - Conclusion: don't install illuminate/database v5.7.3
    - Conclusion: don't install illuminate/database v5.7.2
    - Conclusion: don't install illuminate/database v5.7.1
    - Conclusion: don't install illuminate/database v5.7.0
    - Installation request for laravel/framework (locked at v5.8.18, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.18].
    - rinvex/laravel-addresses v1.0.2 requires illuminate/database ~5.7.0 -> satisfiable by illuminate/database[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - rinvex/laravel-addresses v1.0.1 requires illuminate/database ~5.7.0 -> satisfiable by illuminate/database[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - rinvex/laravel-addresses v1.0.0 requires illuminate/database ~5.7.0 -> satisfiable by illuminate/database[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - Conclusion: don't install illuminate/database 5.7.x-dev
    - Installation request for rinvex/laravel-addresses ^1.0 -> satisfiable by rinvex/laravel-addresses[v1.0.0, v1.0.1, v1.0.2].
`

**Comment by Omranic** [comment]
which tag you're trying to install?
since latest stable release is working fine with Laravel v5.8

**Comment by Omranic** [comment]
Latest stable release is compatible with Laravel v5.8
If you still have any issues, feel free to open a new issue and would love to help..
