### ISSUE TITLE
L ^6.2 Publish error

### ISSUE THREAD

**Issue by AEK-BKF** [rinvex/addresses#32]
Hi,
Using L^6.2, an error on publishing config and migrations files :

> ***********************************************
> *     Publish Rinvex Addresses Resources.     *
> ***********************************************
> 
> Unable to locate publishable resources.
> Publishing complete.
> Unable to locate publishable resources.
> Publishing complete.

**Comment by Omranic** [comment]
Which version you're using?

**Comment by Omranic** [comment]
I believe this issue is with the latest release, which supports Laravel v7.x.
If so then it has been fixed in the latest v4.x release. Otherwise feel free to reopen this issue again with more details so we can help..
