### ISSUE TITLE
Caching enabled by default

### ISSUE THREAD

**Issue by ju5t** [rinvex/addresses#35]
Is there a reason to enable caching by default?

We don't need or rely on caching in our application. We had some weird issues during development which turned out to be related to the cache that's enabled in the model. As we inherited the model and made our changes to the fillable and rules attributes, we ran into unexpected issues.

Would you accept a PR that removes caching by default and allows you to add it if you inherit the class? I do realise that this is a major change as it can have unexpected issues in other applications, but it makes more sense in my mind as it gives more flexibility.

**Comment by Omranic** [comment]
Thank you @ju5t for your suggestion.

Yes, I agree. We've been discussing this for the past period, and an update has been pushed to this repo and all other packages today https://github.com/rinvex/laravel-addresses/commit/07d45a5edd6240765762fc3d4b44e9e39f4ae679

A new release will be tagged soon!

**Comment by ju5t** [comment]
That was fast 👍 

Thanks a lot!
