### ISSUE TITLE
Unable to install in Laravel 7 / PHP version

### ISSUE THREAD

**Issue by yasirmturk** [rinvex/addresses#37]
our requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.16.1
    - Conclusion: don't install laravel/framework v7.16.1
    - rinvex/laravel-addresses v3.0.0 requires illuminate/database ^6.0.0

**Comment by yasirmturk** [comment]
I tried to use `composer require rinvex/laravel-addresses:dev-develop`
but got conflict in php version
```
[InvalidArgumentException]                                                                                 
  Package rinvex/laravel-addresses at version dev-develop has a PHP requirement incompatible with your PHP   
  version (7.3.16)

**Comment by devchalkie** [comment]
Hi there,
Any update on this one?

**Comment by yasirmturk** [comment]
Yes, if you are using PHP `7.3.0+` then;
add this section to your `composer.json`
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/yasirmturk/laravel-addresses"
        },
        {
            "type": "vcs",
            "url": "https://github.com/yasirmturk/countries.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/yasirmturk/laravel-support.git"
        }
    ]
```
and install using `composer require rinvex/laravel-addresses:dev-develop`

**Comment by devchalkie** [comment]
I am getting this error now :
GitHub API limit (0 calls/hr) is exhausted, could not fetch https://api.github.com/repos/yasirmturk/laravel-addresses/contents/composer.json?ref=96ba09715f534eceda7ddaa7122d9851f9d317b
6. Create a GitHub OAuth token to go over the API rate limit. You can also wait until ? for the rate limit to reset.

**Comment by Omranic** [comment]
This package requires PHP v7.4+ 

If you can't afford that version, feel free to install v3.x of this package, or fork and lower the dependencies to fit your needs :)
