### ISSUE TITLE
How to enable soft deletes?

### ISSUE THREAD

**Issue by MHassanSaqib** [rinvex/addresses#41]
Hi there,

Is there any way to enable the soft delete functionality? I am checking the tables, there is a column of deleted_at but I couldn't find how to enable it. I have also checked the configuration file. How can we add configurable variable for it?

**Comment by Omranic** [comment]
Yes we have that field `deleted_at` added into database table, but this functionality wasn't tested on this package before. You'll need to check Laravel documentation and possibly override the model if any custom logic is needed. https://laravel.com/docs/8.x/eloquent#soft-deleting
