### ISSUE TITLE
Support Laravel 8

### ISSUE THREAD

**Issue by anardil** [rinvex/addresses#44]
Hi,

Do you plan to support Laravel 8?

Thanks.

**Comment by anardil** [comment]
Hi,

Any news?

Thanks.

**Comment by jonaths** [comment]
I would appreciate as well support for Laravel 8. Thanks!

**Comment by marqusG** [comment]
Me too :)

**Comment by goshku** [comment]
Any news?

**Comment by Omranic** [comment]
Hello, thank you for your patience, this is now done! Check latest major release!!

This package now supports Laravel v8, PHP v8, Composer v2, enjoy 🥳

CC @gstamosbg @marqusG @jonaths @anardil
