### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by marvinosswald** [rinvex/addresses#52]
`https://github.com/felixkiss/uniquewith-validator` is still php 7 bound, maybe drop the dependency as it seems stale.
Sadly like this your fantastic lib isn't compatible with php 8.

**Comment by Omranic** [comment]
`felixkiss/uniquewith-validator` is not required by this package, in fact none of our packages require it.

We're using a forked version `rinvex/tmp-felixkiss-uniquewith-validator` for all latest releases which is compatible with PHP v8.

Make sure you're trying latest release of the package, and let me know if you still believe there's a compatibility issue.

**Comment by marvinosswald** [comment]
I see, thanks for taking the time. I've went down my composer requirements rabbit hole and found the issue being that you locked the required php version to `v8.0.0` here : https://github.com/rinvex/tmp-watson-validating/blob/master/composer.json#L17 you probably want this to be more open to future php 8 versions.

But i'm on 8.0.1 by now system wide.

created a PR: https://github.com/rinvex/tmp-watson-validating/pull/1

**Comment by Omranic** [comment]
Thank you for catching this, PR merged 👍
