### ISSUE TITLE
Adding Mutators & Accessors

### ISSUE THREAD

**Issue by ferasallaou** [rinvex/addresses#56]
I've a question on how can we add Mutators & Accessors for the data stored using this package, imagine that I want to encrypt the addresses before storing them, is it doable?

**Comment by Omranic** [comment]
Thank you @ferasallaou for your question, yes it is doable using the default Laravel Eloquent way, since this package is using native Laravel Eloquent models, [check here](https://laravel.com/docs/8.x/eloquent-mutators)

Feel free to reopen this issue if you still have any further questions.

**Comment by ferasallaou** [comment]
Thanks @Omranic for your reply.
I tried before opening this ticket to use Mutators without any luck. I'm using the trait like this in my model
`use Addressable;`

and then tried something Like
```
    public function setAddressesAttribute($value)
    {
        $this->attributes['addresses'] = Crypt::encryptString($value);
    }

//OR

    public function setAddressAttribute($value)
    {
        $this->attributes['address'] = Crypt::encryptString($value);
    }
```
I don't know if I'm missing anything here.

**Comment by Omranic** [comment]
Did you change your model in config to your custom one?
https://github.com/rinvex/laravel-addresses/blob/master/config/config.php#L17
