### ISSUE TITLE
I added new fields using migration but those fields didn't save record.

### ISSUE THREAD

**Issue by arslbbt** [rinvex/addresses#59]
I added new fields using migration but those fields didn't save records. Please let me know is it possible or not?

**Comment by Omranic** [comment]
Yes it is possible. You will need to update the `$fillable` array of your eloquent model, check [Laravel docs for more details](https://laravel.com/docs/8.x/eloquent#mass-assignment).

Feel free to reopen this issue if you need further assistance.

**Comment by arslbbt** [comment]
@Omranic yeah I know about `fillable` but how I override the package `fillable`

**Comment by Omranic** [comment]
You can simply add `$fillable` variable in your model, that will override it. Another alternative way is to use `mergeFillable()` method in your model constructor, which allows you to add additional fillable without overriding the original ones.

Once you have your custom model ready, you can change the default model in the package config file https://github.com/rinvex/laravel-addresses/blob/master/config/config.php#L17
